{{- if and (or (.Files.Glob "files/3.5/init/*.sql") .Values.initdbScripts) (not .Values.initdbScriptsConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.appName }}-db-scripts
    labels:
        environment: {{ .Values.global.environment }}
        app: {{ .Values.global.product }}
        tier: {{ .Values.appName }}
data:
{{- with .Files.Glob "files/3.5/init/*.sql" }}
{{ .AsConfig | indent 8 }}
{{- end }}
{{- with .Values.initdbScripts }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.appName }}-init-scripts
data:
    init.sh: |-
{{ .Files.Get "files/init.sh" | indent 8 }}