{{- if .Values.global.db.internal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.secretName }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
type: Opaque
data:
  postgres_dbhost: {{ .Values.appName | b64enc | quote }}
  postgres_dbport: {{ .Values.global.db.dbport | b64enc | quote }}
  postgres_dbsuperuser: {{ .Values.global.db.dbsuperuser | b64enc | quote }}
  postgres_dbsuperuserpwd: {{ .Values.global.db.dbsuperuserpwd | b64enc | quote }}
  postgres_dbuser: {{ .Values.global.db.dbuser | b64enc | quote }}
  postgres_dbpwd: {{ .Values.global.db.dbpwd | b64enc | quote }}
{{- end}}
