apiVersion: v1
name: corezoid
version: 0.14
appVersion: 5.4.1
description: Chart for Corezoid.
home: https://corezoid.com/
engine: gotpl
icon: https://corezoid.com/static/ce1da2c78726bb5ce1cf53b002dac519/62341/CorezoidProduct.png
