apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName}}
    service: {{ .Values.appName }}
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        environment: {{ .Values.global.environment }}
        app: {{ .Values.global.product }}
        tier: {{ .Values.appName}}
        service: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.registry }}/{{ .Values.global.repotype }}/{{ .Values.global.license }}:latest
          ports:
          - containerPort: 5010

