{{- if eq .Values.global.ingress "nginx" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: {{ .Values.global.environment }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.org/websocket-services: "capi-service"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.global.subdomain }}.{{ .Values.global.domain }}
      secretName: ssl
  rules:
    - host: {{ .Values.global.subdomain }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: corezoid-web-adm
              servicePort: 80
          - path: /api/[0-9]/sock_json
            backend:
              serviceName: capi-service
              servicePort: 9080
          - path: /api/1/sock_json
            backend:
              serviceName: capi-service
              servicePort: 9080
{{- end }}