{{- if eq .Values.global.ingress "nginx" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: {{ .Values.global.environment }}
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
{{- end }}