{{- if not .Values.global.secretalreadyexist }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
stringData:
  redis_host: ""
  redis_port: ""
  redis_password: "0"
  mq_host: ""
  mq_port: ""
  mq_vhost: "/conveyor"
  mq_username: "app-user"
  mq_password: ""
  elasticsearch_host: ""
  elasticsearch_port: "443"

  postgres_dbhost: ""
  postgres_dbuser: "internal_user"
  postgres_dbpwd: ""
  postgres_dbsuperuser: "postgres"
  postgres_dbsuperuserpwd: ""
  postgres_dbport: "5432"
  superuser_passwd: "admin111"
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
    name: license-share-new
type: Opaque
data:
        {{- $root := . -}}
        {{- range $path, $bytes := .Files.Glob "license/corezoid_license" }}
        corezoid_license: '{{ $root.Files.Get $path | b64enc }}'
        {{- end }}
