apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 9082
    targetPort: 9082
