apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      tier: {{ .Values.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.global.syncapi.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/syncapi-configmap.yaml") . | sha256sum }}
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Values.global.product }}
        tier: {{ .Values.appName }}
    spec:
      terminationGracePeriodSeconds: 120
      initContainers:
        - name: init-wait-rmq
          image: alpine
          command: ['sh']
          args:
            - "-c"
            - |
              until wget -O - -q --header "Authorization: Basic `echo -n \"$MQ_USERNAME:$MQ_PASSWORD\" | base64`" http://{{- if .Values.global.mq.internal }}rabbit-service{{- else }}${MQ_HOST}{{- end }}:15672/api/exchanges/%2Fconveyor/ | grep -qF "conf_agent_direct"; do echo "waiting for exchanges to be ready..."; sleep 2; done
          env:
            {{- if and ( .Values.global.mq.secretName ) ( not .Values.global.mq.internal) }}
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_host
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_username
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_password
            {{- else}}
            - name: MQ_HOST
              value: {{ .Values.global.mq.host }}
            - name: MQ_USERNAME
              value: {{ .Values.global.mq.username }}
            - name: MQ_PASSWORD
              value: {{ .Values.global.mq.password }}
            {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.registry }}/{{ .Values.global.repotype}}{{ .Values.image.repository }}:{{ .Values.global.syncapi.tag }}"
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.global.debug }}
            - name: ERL_CRASH_DUMP
              value: "/dev/stderr"
            {{- end }}
            - name: RELX_REPLACE_OS_VARS
              value: "true"
            {{- if and ( .Values.global.mq.secretName ) ( not .Values.global.mq.internal) }}
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_host
            - name: MQ_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_port
            - name: MQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_vhost
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_username
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mq.secretName }}
                  key: mq_password
            {{- else }}
            - name: MQ_HOST
              value: {{ .Values.global.mq.host }}
            - name: MQ_PORT
              value: {{ .Values.global.mq.port | quote }}
            - name: MQ_VHOST
              value: {{ .Values.global.mq.vhost }}
            - name: MQ_USERNAME
              value: {{ .Values.global.mq.username }}
            - name: MQ_PASSWORD
              value: {{ .Values.global.mq.password }}
            {{- end }}
            - name: POSTGRES_DBHOST
              {{- if .Values.global.db.bouncer }}
              value: "pgbouncer-service"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: postgres_dbhost
            {{- end }}
            - name: POSTGRES_DBUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: postgres_dbuser
            - name: POSTGRES_DBPWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: postgres_dbpwd
            - name: POSTGRES_DBPORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: postgres_dbport

          ports:
            - containerPort: 8090
          lifecycle:
            preStop:
              exec:
                command: ["/ebsmnt/erlang/corezoid_api_sync/bin/corezoid_api_sync","stop"]
          volumeMounts:
            - name: {{ .Values.appName }}-config
              mountPath: /ebsmnt/conf/corezoid_api_sync.config
              subPath: corezoid_api_sync.config
          resources:
            {{ .Values.global.syncapi.resources | toYaml | indent 12 | trim }}
          livenessProbe:
            httpGet:
              path: /is_ready
              port: 8383
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /is_ready
              port: 8383
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      {{- if not  (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: corezoid-secret
      {{- end }}
      volumes:
        - name: {{ .Values.appName }}-config
          configMap:
            name: {{ .Values.appName }}-config

