apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-{{ .Release.Namespace }}
{{- if .Values.global.ingress.annotations }}
  annotations:
{{ toYaml .Values.global.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-adm
              servicePort: 80
    - host: {{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-superadm
              servicePort: 80
    - host: {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: syncapi-main
              servicePort: 8090
    {{- if .Values.global.sa.enabled }}
    - host: {{ .Values.global.sa_web.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: single-account-web
              servicePort: 80
    {{- end }}
    {{- if .Values.global.mq.external }}
    - host: {{ .Values.global.mq.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /{{ .Values.global.mq.basePath }}/*
            backend:
              serviceName: rabbit-external
              servicePort: 15672
    {{- end }}