apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
type: Opaque
data:
  capi_api_secret: {{ .Values.global.capi.capi_api_secret | b64enc | quote }}
  capi_auth_hash: {{ .Values.global.capi.capi_auth_hash | b64enc | quote }}
