apiVersion: v1
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log /dev/stdout;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  512000;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        log_format up_log '$server_addr\t$server_port\t$http_x_forwarded_for\t$time_iso8601\tforward-to $upstream_addr\t$request\t$status\t$body_bytes_sent\t$request_time\t$upstream_response_time\t$http_referer\t$http_user_agent\t$http_cookie\t$host';
        access_log /dev/stdout up_log;
        real_ip_header      X-Forwarded-For;
        set_real_ip_from    0.0.0.0/0;
        limit_req_zone $binary_remote_addr zone=one:20m rate=1r/s;
        limit_req_zone $binary_remote_addr zone=five:20m rate=5r/s;
        limit_req_zone $binary_remote_addr zone=ten:20m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=fifteen:20m rate=15r/s;
        limit_req_zone $binary_remote_addr zone=fifty:20m rate=50r/s;
        limit_req_zone $binary_remote_addr zone=hundred:20m rate=100r/s;
        limit_req_zone $binary_remote_addr zone=twohundred:20m rate=200r/s;
        limit_req_zone $binary_remote_addr zone=fivehundred:20m rate=500r/s;
        sendfile        on;
        #tcp_nopush     on;
        server_tokens   off;
        #keepalive_timeout  0;
        keepalive_timeout  65;
        include /etc/nginx/conf.d/*.conf;
    }
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-main
