apiVersion: v1
data:
  corezoid.conf: |
    map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
    }


    server {
        listen 80;
        server_name default_server;

        add_header X-Frame-Options SAMEORIGIN;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";


        large_client_header_buffers     4 16k;
        client_body_buffer_size 16k;
        client_max_body_size 16m;

        set $static_root    "/usr/share/nginx/html/capi-js";
        set $admin_root    "/usr/share/nginx/html";
        set $static_local    "/usr/share/nginx/html/static";

         location = /ping { return 200; }

        if ( $http_x_forwarded_proto != "https") {
            rewrite ^/(.*)$   https://$host/$1    break;
        }


        location /avatars {
            add_header      Content-Type image/jpeg;
            error_page  404  =200   /avatars/0.jpg;
            root $static_local;
        }

        location /favicon/ {
           root /usr/share/nginx/html;
        }

        location /logo/ {
           root /usr/share/nginx/html;
        }

        location = /favicon.ico { return 200; }

        location / {
            root $admin_root;
            try_files $uri /index.html;
        }

        location ~ ^/editor {
            root $admin_root;
            try_files $uri /editor.html;
        }

        location ~^/dashboard {
            root $admin_root;
            try_files $uri /dashboard.html;
        }

        location ~ ^/health {
            root $admin_root;
            try_files $uri /health.html;
        }

        # web
        location ~ ^/api/[0-9]/sock_json {
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            #proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        # api
        location ~ ^/api/[0-9]/json {
            limit_req zone=hundred burst=50;
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            #proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        # multipart_worker
        location ~ ^/api/2/(download|upload) {
            proxy_pass http://mult-service:9082;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_buffering off;
            proxy_intercept_errors on;
            #proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location /user_downloads {
            limit_req zone=hundred burst=500;
            proxy_pass http://mult-service:9082;
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_intercept_errors on;
            #proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }
        location /auth {
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_pass http://capi-service:9080;
        }

        location /system {
            add_header X-Content-Type-Options "text/html";
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_pass http://capi-service:9080;
            proxy_connect_timeout     360;
            proxy_read_timeout        360;
            proxy_send_timeout        720;
        }


    }
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-site
