apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
type: Opaque
data:
  merchant_login: {{ .Values.global.merchant.merchant_login | b64enc | quote }}
  merchant_secret: {{ .Values.global.merchant.merchant_secret | b64enc | quote }}
