---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    environment: {{ .Values.global.environment }}
    app: {{ .Values.global.product}}
    tier: {{ .Values.appName }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: {{ .Values.global.environment }}
        app: {{ .Values.global.product }}
        tier: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: app-user
          - name: RABBITMQ_DEFAULT_PASS
            value: password
          - name: RABBITMQ_DEFAULT_VHOST
            value: /conveyor

          image: {{ .Values.image.registry }}/{{ .Values.global.repotype }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: {{ .Values.appName }}
              protocol: TCP
              containerPort: 5672
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 150m
              memory: 300Mi
            {{- if not  (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
        {{- end }}
